### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by raayu83** [ambient-innovation/django-migration-zero#7]
This package sounds very interesting, but I wonder if it is Production Ready and Battle Tested?
Are there any sitations where things could break because of using this package?

**Comment by GitRon** [comment]
Hi @raayu83! We use it in a handful of projects. Since the "magic" is quite simple, I guess you could put it like this: Test it locally and if it works, I'll work in production as well.

Would be awesome to get some feedback from you when you're trying it out 🙂

**Comment by zentek-philip** [comment]
We actually use it in production without problems! A local test is always advised of course!

**Comment by GitRon** [comment]
Hi @raayu83! I hope the answers satisfy you. Please feel free to drop any questions here. Since I don't know if there are any left, I'll close this ticket.
